const mongoose = require('mongoose');

const quizSchema = new mongoose.Schema({
    title: { type: String, required: true },
    course: { type: String, required: true }, // The frontend mockup just has a 'course' field (e.g. "ITPM")
    description: { type: String },
    dueDate: { type: Date },

    teacher: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

    // The questions generated by AI and stored
    questions: [{
        questionText: { type: String, required: true },
        type: { type: String, enum: ['MCQ', 'Essay', 'Structured'], required: true },

        // For MCQ
        options: [{ type: String }],
        correctAnswer: { type: mongoose.Schema.Types.Mixed }, // String for MCQ, String or criteria for Essay/Structured

        marks: { type: Number, required: true, default: 1 }
    }],

    totalMarks: { type: Number, default: 0 },
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Quiz', quizSchema);
